
services:
  Alias_site:
    image: python:3.12
    working_dir: /app
    ports:
      - 5454:5454
    command: >
      /bin/bash -c "pip install -q -r requirements.txt && python main.py"
    volumes:
      - .:/app
    restart: unless-stopped




